// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfvSy2FSizqUwTpfuZZhyMRZ8d8hlyKfg',
    appId: '1:876682300208:web:6659501e4d5f25990996f5',
    messagingSenderId: '876682300208',
    projectId: 'notes-afe85',
    authDomain: 'notes-afe85.firebaseapp.com',
    storageBucket: 'notes-afe85.firebasestorage.app',
    measurementId: 'G-0SSB8SEJ5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoM9r3Ti5X3mA7oZyhcUd8Mj1abfSvCHg',
    appId: '1:876682300208:android:234e3ae21b51c26d0996f5',
    messagingSenderId: '876682300208',
    projectId: 'notes-afe85',
    storageBucket: 'notes-afe85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfMS6i8ndVMiS_xBi-SReD0NbLeRRWDko',
    appId: '1:876682300208:ios:2b58815fa285fc120996f5',
    messagingSenderId: '876682300208',
    projectId: 'notes-afe85',
    storageBucket: 'notes-afe85.firebasestorage.app',
    iosBundleId: 'com.example.coreticoFirebasenote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfMS6i8ndVMiS_xBi-SReD0NbLeRRWDko',
    appId: '1:876682300208:ios:2b58815fa285fc120996f5',
    messagingSenderId: '876682300208',
    projectId: 'notes-afe85',
    storageBucket: 'notes-afe85.firebasestorage.app',
    iosBundleId: 'com.example.coreticoFirebasenote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfvSy2FSizqUwTpfuZZhyMRZ8d8hlyKfg',
    appId: '1:876682300208:web:e7d594dec1eaf6c00996f5',
    messagingSenderId: '876682300208',
    projectId: 'notes-afe85',
    authDomain: 'notes-afe85.firebaseapp.com',
    storageBucket: 'notes-afe85.firebasestorage.app',
    measurementId: 'G-LJC6C5EK9D',
  );
}
